import = [
  "~/.config/alacritty/themes/themes/gnome_terminal.toml",
  "C:\\Users\\Alex\\AppData\\Roaming\\alacritty\\themes\\themes\\gnome_terminal.toml"
]

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Bold"  }
italic = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Italic"  }
bold_italic = { family = "JetBrainsMonoNL Nerd Font Propo", style = "Bold Italic"  }

